# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="juanger"
export DISABLE_AUTO_UPDATE="true"

source $ZSH/oh-my-zsh.sh

TEXLIVE_PATH=/usr/local/texlive/2012basic/bin/universal-darwin
BREW_PATH=/usr/local/bin:/usr/local/sbin
RBENV_PATH="$HOME/.rbenv/bin"

export PATH=$RBENV_PATH:$BREW_PATH:$PATH:$TEXLIVE_PATH

unsetopt correct_all
eval "$(rbenv init -)"

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
